### ISSUE TITLE
 Redundant rest_framework.urls?

### ISSUE THREAD

**Issue by zhan9san** [pymike00/QuestionTime#11]
`rest_framework.urls` is a proper subnet of `django.contrib.auth.urls`, especially 'login' and 'logout'.

Now that `django.contrib.auth.urls` is included, could you please let me know why should we include `rest_framework.urls` either?

Both use the same view class, django.contrib.auth.views. The difference is the template, and I notice that the template `registration/login.html` for `django.contrib.auth.urls` is customized.

Could you please help explain where rest_framework.urls is used?

Reference:
https://github.com/django/django/blob/master/django/contrib/auth/urls.py
https://github.com/encode/django-rest-framework/blob/master/rest_framework/urls.py

In any event, I am very grateful for your assistance.

**Comment by pymike00** [comment]
Are you referring to api-auth/ ?

https://github.com/pymike00/QuestionTime/blob/master/QuestionTime/QuestionTime/urls.py#L38

We use that to perform authentication via the browsable API!

Best.
