### ISSUE TITLE
VScode can not find django_registration

### ISSUE THREAD

**Issue by anqoVoube** [pymike00/QuestionTime#35]
![Problem](https://user-images.githubusercontent.com/91607120/139591748-fa32c4e9-c735-4023-92e4-a76b57d2e15c.png)
I did install django_registration in my environment, I mean everything like in the course. Moreover, the same issue occurred when I tried to run your already done project with full installed packages. I tried to reinstall it 3 times. however, this didn't help to solve that issue.

**Comment by pymike00** [comment]
Sorry about late answer, I wasn't expecting questions about the course here on GitHub.

The issue seems more related to a VS Code misconfiguration than else.

Closing.
